container:
  image: cirrusci/flutter:latest

test_task:
  #pub_cache:
    # folder: $HOME/.pub-cache
    # fingerprint_script: cat pubspec.lock
    # populate_script: pub get
  pub_script: pub get
  format_script: dartfmt **/*.dart -n --set-exit-if-changed
  analyze_script: dartanalyzer --fatal-infos .
  publishable_script: pub publish --dry-run
  test_script:
  - pub global activate coverage
  - dart --enable-vm-service=8111 --pause-isolates-on-exit test/* &
  - pub global run coverage:collect_coverage --port=8111 --out=coverage.json --wait-paused --resume-isolates
  - bash <(curl -s https://codecov.io/bash)
