name: uuid_enhanced
version: 3.0.2
description: >
  RFC4122 (v1, v4, v5) UUID Generator and Parser for all Dart platforms (Web, VM, Flutter)
authors: 
  - Yulian Kuncheff <yulian@kuncheff.com>
  - TruongSinh Tran-Nguyen <i@truongsinh.pro>
homepage: https://github.com/truongsinh/dart-uuid
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  crypto: ">=2.0.0 <3.0.0"
  convert: ^3.0.0-nullsafety
  collection: ^1.15.0-nullsafety
dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
dependency_overrides:
  convert: ^3.0.0-nullsafety
  crypto:
    git: https://github.com/dart-lang/crypto.git